### ISSUE TITLE
panic with HTTP PUT on python SimpleHTTPServer

### ISSUE THREAD

**Issue by kr** [inconshreveable/ngrok#178]
I get a panic when PUTting a gzip file to python's SimpleHTTPServer, which doesn't support the PUT method.

#### Step 1

```
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

#### Step 2

```
$ ngrok 8000
ngrok                                                           (Ctrl+C to quit)
                                                                                
Tunnel Status                 online                                            
Version                       1.7/1.6                                           
Forwarding                    http://5bcd20f7.ngrok.com -> 127.0.0.1:8000       
Forwarding                    https://5bcd20f7.ngrok.com -> 127.0.0.1:8000      
Web Interface                 127.0.0.1:4040                                    
# Conn                        0                                                 
Avg Conn Time                 0.00ms                                            
```

#### Step 3

Upload a gzip file. I think the contents are not important, but I tried a zero-length file, and it doesn't reliably reproduce the bug for me.

```
$ ls -l bin
total 93488
-rwxr-xr-x  1 kr  staff   8761468 Nov  7 19:34 godep
-rwxr-xr-x  1 kr  staff   4870624 Nov  7 19:33 goimports
-rwxr-xr-x  1 kr  staff   5601168 Nov 10 15:17 golint
-rwxr-xr-x  1 kr  staff   7718356 Nov  7 19:26 link
-rwxr-xr-x@ 1 kr  staff  13122356 Nov 30  1979 ngrok
-rwxr-xr-x  1 kr  staff   7777108 Nov 11 14:50 wsnote
$ tar cf bin.tar bin
$ gzip bin.tar 
$ curl -T bin.tar.gz https://5bcd20f7.ngrok.com
```

## Expected results

I see an HTTP 5xx error message in both the python and ngrok output.

## Actual results

```
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [11/Nov/2014 16:21:30] code 501, message Unsupported method ('PUT')
127.0.0.1 - - [11/Nov/2014 16:21:30] "PUT /bin.tar.gz HTTP/1.1" 501 -
```

```
goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc210058f80)
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 27 [runnable]:
ngrok/proto.(*Http).readResponses(0xc210041500, 0xc21034cb90, 0xc2103152a0)
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:104 +0x67
created by ngrok/proto.(*Http).WrapConn
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:67 +0xc3

goroutine 29 [semacquire]:
sync.runtime_Syncsemacquire(0xc21033a678)
	/Users/aes/src/gonative/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc21033a668)
	/Users/aes/src/gonative/go/src/pkg/sync/cond.go:62 +0x89
io.(*pipe).write(0xc21033a600, 0xc2103af000, 0x29, 0x8000, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/io/pipe.go:94 +0x1fe
io.(*PipeWriter).Write(0xc210354978, 0xc2103af000, 0x29, 0x8000, 0x29, ...)
	/Users/aes/src/gonative/go/src/pkg/io/pipe.go:161 +0x5f
io.(*teeReader).Read(0xc21034dbe0, 0xc2103af000, 0x8000, 0x8000, 0x29, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:487 +0xd3
ngrok/conn.(*Tee).Read(0xc21034cb90, 0xc2103af000, 0x8000, 0x8000, 0x8000, ...)
	/Users/aes/src/ngrok/src/ngrok/conn/tee.go:62 +0x64
io.Copy(0xb13140, 0xc210337300, 0xb21bf0, 0xc21034cb90, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:352 +0x1c8
ngrok/conn.func·002(0xb12f68, 0xc210337300, 0xb21a80, 0xc21034cb90, 0xc210354998)
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:204 +0x142
created by ngrok/conn.Join
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:215 +0x131
```

(Apologies for the incomplete stack trace. The terminal is left in raw mode during the panic.)

**Comment by inconshreveable** [comment]
old issue, closing. never fixed in 1.x, but is fixed in 2.x
