### ISSUE TITLE
File Upload via Ngrok using nodejs Breaks

### ISSUE THREAD

**Issue by byteshiva** [inconshreveable/ngrok#216]
File Upload via Ngrok using nodejs Breaks

```
              goroutine 45 [select]:
                                    net/http.(*persistConn).writeLoop(0x18cf6190)
                                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:791 +0x207
                              created by net/http.(*Transport).dialConn
                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:529 +0x4dc

              goroutine 56 [select]:
                                    net/http.(*persistConn).writeLoop(0x18cf6d20)
                                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:791 +0x207
                              created by net/http.(*Transport).dialConn
                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:529 +0x4dc

              goroutine 64 [chan receive]:
                                          net/http.(*persistConn).readLoop(0x18c451e0)
                                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:701 +0x24b
                              created by net/http.(*Transport).dialConn
                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:528 +0x4c7

              goroutine 65 [select]:
                                    net/http.(*persistConn).writeLoop(0x18c451e0)
                                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:791 +0x207
                              created by net/http.(*Transport).dialConn
                                                                        /Users/aes/src/gonative/go/src/pkg/net/http/transport.go:529 +0x4dc

```

adding more error logs

```
x72, 0x0)
                /Users/aes/src/gonative/go/src/pkg/runtime/netpoll.goc:116 +0x61
                                                                                net.(*pollDesc).Wait(0x18c70978, 0x72, 0xb77568a8, 0xb)
                /Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:81 +0x35
                                                                                  net.(*pollDesc).WaitRead(0x18c70978, 0xb, 0xb77568a8)
                /Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:86 +0x33
                                                                                  net.(*netFD).Read(0x18c70940, 0x18b1d000, 0x8000, 0x8000, 0x0, ...)
                        /Users/aes/src/gonative/go/src/pkg/net/fd_unix.go:204 +0x234
                                                                                    net.(*conn).Read(0x18c84f80, 0x18b1d000, 0x8000, 0x8000, 0xb774e000, ...)
                                /Users/aes/src/gonative/go/src/pkg/net/net.go:122 +0xab
                                                                                       ngrok/conn.(*loggedConn).Read(0x18c74460, 0x18b1d000, 0x8000, 0x8000, 0x82a3680, ...)
                                                /Users/aes/src/ngrok/src/ngrok/conn/conn.go:1 +0x5d
                                                                                                   io.(*teeReader).Read(0x18c826d0, 0x18b1d000, 0x8000, 0x8000, 0x8333140, ...)
                                                        /Users/aes/src/gonative/go/src/pkg/io/io.go:485 +0x58
                                                                                                             ngrok/conn.(*Tee).Read(0x18c754e0, 0x18b1d000, 0x8000, 0x8000, 0x0, ...)
                                                        /Users/aes/src/ngrok/src/ngrok/conn/tee.go:62 +0x58
                                                                                                           io.Copy(0xb7758318, 0x18c66d00, 0xb775d4b8, 0x18c754e0, 0x0, ...)
                                                /Users/aes/src/gonative/go/src/pkg/io/io.go:352 +0x177
                                                                                                      ngrok/conn.func·002(0xb7758018, 0x18c66d00, 0xb775d3e8, 0x18c754e0, 0x18c7a018)
                                                        /Users/aes/src/ngrok/src/ngrok/conn/conn.go:204 +0xfe
                                                                                                             created by ngrok/conn.Join
                /Users/aes/src/ngrok/src/ngrok/conn/conn.go:215 +0xf4

```

refer : https://github.com/inconshreveable/ngrok/issues/200

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
