### ISSUE TITLE
ngrok on bash on ubuntu on windows 10

### ISSUE THREAD

**Issue by leohartx** [inconshreveable/ngrok#364]
hi , i downloaded ngrok for linux 64 bit from ngrok.com and tried to run it within bash on ubuntu on  windows 10 (ubuntu LTS 14.04 64 bit), it failed to start and there was no trace or error output. is there any way to see ngrok startup log ?

i'm looking forward to seeing news from you.

Thanks,

**Comment by inconshreveable** [comment]
ngrok doesn't support running on windows bash yet (it's still in beta). this will be supported eventually when that product is stable.

this is not an issue with the 1.x open source project, closing.

**Comment by bencooper222** [comment]
Sorry to reopen but does this work yet?

**Comment by dandunckelman** [comment]
I just hit this w/ this error output:

```
$ ngrok
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x727b53]

goroutine 1 [running, locked to thread]:
runtime.throw(0xa632b3, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420039790 sp=0xc420039770
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc4200397e8 sp=0xc420039790
github.com/go-stack/stack.findSigpanic.func1(0x0, 0xc420039828, 0x0)
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:228 +0x53 fp=0xc420039810 sp=0xc4200397e8
github.com/go-stack/stack.findSigpanic(0xa72801)
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:229 +0x3d fp=0xc420039840 sp=0xc420039810
github.com/go-stack/stack.init()
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:233 +0xa2 fp=0xc420039870 sp=0xc420039840
github.com/inconshreveable/log15.init()
        /Users/aes/src/ngrok/vendor/src/github.com/inconshreveable/log15/syslog.go:56 +0x80 fp=0xc4200398b0 sp=0xc420039870
lib/shared.init()
        /Users/aes/src/ngrok/src/lib/shared/version.go:15 +0x47 fp=0xc4200398b8 sp=0xc4200398b0
main.init()
        /Users/aes/src/ngrok/src/ngrok/web_ui.go:568 +0x8d fp=0xc420039f48 sp=0xc4200398b8
runtime.main()
        /usr/local/go/src/runtime/proc.go:172 +0x1bf fp=0xc420039fa0 sp=0xc420039f48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420039fa8 sp=0xc420039fa0
```

Trying to find a fix now

**Comment by dandunckelman** [comment]
Workaround for me was to download the windows binary of ngrok and run it from powershell.

**Comment by mbardelmeijer** [comment]
Any idea when support will land for Bash on Windows? Bash on Windows will stay in beta for a while, would be awesome to see this supported. nginx, php-fpm etc. work fine, so could be a full-stop dev environment 😄

**Comment by ChrisHines** [comment]
This should be fixed upstream: https://github.com/go-stack/stack/releases/tag/v1.5.4
