### ISSUE TITLE
After ngrokd run, the client exits Error

### ISSUE THREAD

**Issue by hauntek** [inconshreveable/ngrok#365]
I golang 1.7 cross compiler to run the server running, but the client service side exit diary error?

Error Log:
```
Control::reader failed with error read tcp 127.0.0.1:4443->127.0.0.1:61933: wsarecv: An existing connection was forcibly closed by the remote host.: goroutine 5 [running]:
runtime/debug.Stack(0xc042271e68, 0x70fc00, 0xc042190960)
        D:/Program Files/Go/src/runtime/debug/stack.go:24 +0x80
ngrok/server.(*Control).reader.func1(0xc042164480)
        D:/Program Files/ngrok/src/ngrok/server/control.go:229 +0x61
panic(0x70fc00, 0xc042190960)
        D:/Program Files/Go/src/runtime/panic.go:458 +0x251
ngrok/server.(*Control).reader(0xc042164480)
        D:/Program Files/ngrok/src/ngrok/server/control.go:246 +0x1e9
created by ngrok/server.NewControl
        D:/Program Files/ngrok/src/ngrok/server/control.go:124 +0x9db
```

**Comment by hauntek** [comment]
How to solve this error?

**Comment by inconshreveable** [comment]
the remote server is rejecting the connection attempt for some reason.
