### ISSUE TITLE
2.1.12 segmentation faults regularly

### ISSUE THREAD

**Issue by copiousfreetime** [inconshreveable/ngrok#367]
I just updated ngrok to the latest 2.1.12 automatically and then this is starting to happen every 1 to 3 proxied requests:

```
ngrok by @inconshreveable                                                                                                                                            (Ctrl+C to quit)

Session Status                online
Account                       Jeremy Hinegardner (Plan: Free)
Version                       2.1.12
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://80211b44.ngrok.io -> localhost:3000
Forwarding                    https://80211b44.ngrok.io -> localhost:3000

Connections                   ttl     opn     rt1     rt5     p50     p90
                              0       1       0.00    0.00    0.00    0.00

HTTP Requests
-------------

POST /chargebee/webhook/handler 201 Created
panic: runtime error: invalid memory address or nil pointer dereference
                                                                                                                  [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x268502]

    goroutine 33 [running]:
                           panic(0x523d20, 0xc420016120)
                                                                /usr/local/go/src/runtime/panic.go:500 +0x1a1
                                                                                                             lib/inspect.Responses(0x880b60, 0xc420176918, 0xc420020300, 0xc420524aa0, 0x500000, 0xf962d0, 0xc4204eede0)
                                        /Users/aes/src/ngrok/src/lib/inspect/http.go:179 +0x272
                                                                                               created by lib/inspect.HTTP
                                                                                                                                /Users/aes/src/ngrok/src/lib/inspect/http.go:42 +0x273
```

**Comment by inconshreveable** [comment]
This is fixed, please update to 2.1.14 (`ngrok update`) for a fixed version. It was proximally caused by ngrok not coping with misbehaving webservers (like rails default)
