### ISSUE TITLE
macOS Sierra 10.12 ngrok often crashes

### ISSUE THREAD

**Issue by hteen** [inconshreveable/ngrok#374]
* macOS Sierra 10.12
* ngrok client version 1.7

```linux
panic: sync: inconsistent mutex state

goroutine 511 [running]:
ngrok/util.MakePanicTrace(0x43df00, 0xc820404cb0, 0x0, 0x0)
	/ngrok/src/ngrok/util/errors.go:19 +0x89
ngrok/client.(*Controller).Go.func1.1(0xc82000ad20)
	/ngrok/src/ngrok/client/controller.go:90 +0x5c
panic(0x43df00, 0xc820404cb0)
	/usr/lib/go-1.6/src/runtime/panic.go:426 +0x4e9
sync.(*Mutex).Lock(0xc82000b030)
	/usr/lib/go-1.6/src/sync/mutex.go:75 +0x16d
github.com/rcrowley/go-metrics.(*ExpDecaySample).update(0xc82000b020, 0xecf942dd9, 0x1fd1a73e, 0x896440, 0x1122)
	/ngrok/src/github.com/rcrowley/go-metrics/sample.go:165 +0x43
github.com/rcrowley/go-metrics.(*ExpDecaySample).Update(0xc82000b020, 0x1122)
	/ngrok/src/github.com/rcrowley/go-metrics/sample.go:142 +0x59
github.com/rcrowley/go-metrics.(*StandardHistogram).Update(0xc820011950, 0x1122)
	/ngrok/src/github.com/rcrowley/go-metrics/histogram.go:199 +0x43
ngrok/client.(*ClientModel).proxy.func1()
	/ngrok/src/ngrok/client/model.go:390 +0x22f
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc8201563c0, 0xc8203562a0)
	/ngrok/src/github.com/rcrowley/go-metrics/timer.go:212 +0x3d
ngrok/client.(*ClientModel).proxy(0xc820150dd0)
	/ngrok/src/ngrok/client/model.go:393 +0x10a1
ngrok/client.(*ClientModel).(ngrok/client.proxy)-fm()
	/ngrok/src/ngrok/client/model.go:295 +0x20
ngrok/client.(*Controller).Go.func1(0xc82000ad20, 0xc8203b6740)
	/ngrok/src/ngrok/client/controller.go:96 +0x44
created by ngrok/client.(*Controller).Go
	/ngrok/src/ngrok/client/controller.go:97 +0x3f


Oh noes! ngrok crashed!
```

**Comment by inconshreveable** [comment]
What version of Go did you compile ngrok with?

**Comment by hteen** [comment]
ubuntu:16.04

``` linux
# go version
go version go1.6.1 linux/amd64
```

**Comment by inconshreveable** [comment]
This is a problem with Go. You need 1.6.3 or 1.7: https://golang.org/doc/go1.7#ports
