### ISSUE TITLE
Could not update from 2.1.3 to 2.1.14 via command line

### ISSUE THREAD

**Issue by chrisforrence** [inconshreveable/ngrok#377]
Hello,

When attempting to update ngrok from 2.1.3 to the latest version (2.1.14 at this time) on OS X, I received the following error message:

```
cforrence@localhost ~ $ ngrok version
ngrok version 2.1.3
cforrence@localhost ~  $ ngrok update
Update available! Updating to version 2.1.14 . . .
failed MSpanList_Insert 0x360fcd8 0x7df2077a37b 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x994008, 0x360fcd8)
	/Users/aes/src/ngrok/toolchain/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x9922c0, 0x1, 0x10000000003, 0x59c09)
	/Users/aes/src/ngrok/toolchain/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x998f58, 0x360fc08)
	/Users/aes/src/ngrok/toolchain/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0xa83000, 0xc200000003, 0x360fc08)
	/Users/aes/src/ngrok/toolchain/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:198 fp=0xc2080cc7b8 sp=0xc2080cc7b0
runtime.mallocgc(0x20, 0x467da0, 0x1, 0x0)
	/Users/aes/src/ngrok/toolchain/src/runtime/malloc.go:178 +0x849 fp=0xc2080cc868 sp=0xc2080cc7b8
runtime.newarray(0x467da0, 0x18, 0x57bda0)
	/Users/aes/src/ngrok/toolchain/src/runtime/malloc.go:365 +0xc1 fp=0xc2080cc8a0 sp=0xc2080cc868
runtime.makeslice(0x4555c0, 0x18, 0x18, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/runtime/slice.go:32 +0x15c fp=0xc2080cc8e8 sp=0xc2080cc8a0
encoding/binary.Read(0xaa6128, 0xc20810c400, 0xaa2f78, 0x98a0c8, 0x44a520, 0xc20c72bfe0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/encoding/binary/binary.go:215 +0x12ac fp=0xc2080ccb78 sp=0xc2080cc8e8
github.com/equinox-io/equinox/internal/go-update/internal/binarydist.Patch(0xa96c30, 0xc2082ea010, 0xa95598, 0xc208306070, 0xaa2d08, 0xc208114440, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/internal/go-update/internal/binarydist/patch.go:56 +0x6a9 fp=0xc2080ccd10 sp=0xc2080ccb78
github.com/equinox-io/equinox/internal/go-update.patchFn.Patch(0x75bcd8, 0xa96c30, 0xc2082ea010, 0xa95598, 0xc208306070, 0xaa2d08, 0xc208114440, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/internal/go-update/patcher.go:17 +0x77 fp=0xc2080ccd58 sp=0xc2080ccd10
github.com/equinox-io/equinox/internal/go-update.(*Options).applyPatch(0xc208302090, 0xaa2d08, 0xc208114440, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/internal/go-update/apply.go:288 +0x1e5 fp=0xc2080cce40 sp=0xc2080ccd58
github.com/equinox-io/equinox/internal/go-update.Apply(0xaa2d08, 0xc208114440, 0xc20800b580, 0x14, 0x0, 0xc208234d00, 0x20, 0x20, 0x5bc100, 0xc20800b4a0, ...)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/internal/go-update/apply.go:81 +0x1ea fp=0xc2080cd098 sp=0xc2080cce40
github.com/equinox-io/equinox.Response.Apply(0xc20822b548, 0x6, 0xc20822b580, 0xe, 0x98a0c8, 0x0, 0xecfa026ce, 0x1c3ff4a4, 0x9794e0, 0xc2081f2690, ...)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/sdk.go:285 +0x63d fp=0xc2080cd2d0 sp=0xc2080cd098
main.(*defaultUpdater).RunConsole(0xc2080a6380, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/updater.go:156 +0x48c fp=0xc2080cd680 sp=0xc2080cd2d0
main.runUpdate(0xc2080a60e0)
	/Users/aes/src/ngrok/src/ngrok/cli.go:219 +0x70 fp=0xc2080cd6d0 sp=0xc2080cd680
github.com/inconshreveable/axiom.func·001(0xc2080a60e0)
	/Users/aes/src/ngrok/vendor/src/github.com/inconshreveable/axiom/axiom.go:122 +0x325 fp=0xc2080cd818 sp=0xc2080cd6d0
github.com/codegangsta/cli.Command.Run(0x63e8d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6e7c50, 0x22, 0x769950, ...)
	/Users/aes/src/ngrok/vendor/src/github.com/codegangsta/cli/command.go:118 +0x1044 fp=0xc2080cdc08 sp=0xc2080cd818
github.com/codegangsta/cli.(*App).Run(0xc20810e000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/codegangsta/cli/app.go:177 +0xeaa fp=0xc2080cdf08 sp=0xc2080cdc08
main.main()
	/Users/aes/src/ngrok/src/ngrok/main.go:11 +0x68 fp=0xc2080cdf98 sp=0xc2080cdf08
runtime.main()
	/Users/aes/src/ngrok/toolchain/src/runtime/proc.go:63 +0xf3 fp=0xc2080cdfe0 sp=0xc2080cdf98
runtime.goexit()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080cdfe8 sp=0xc2080cdfe0

goroutine 6 [syscall]:
os/signal.loop()
	/Users/aes/src/ngrok/toolchain/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/Users/aes/src/ngrok/toolchain/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [select]:
main.func·005()
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:76 +0x280
created by main.NewBitcast
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:94 +0x1d8

goroutine 19 [select]:
net/http.(*persistConn).readLoop(0xc20809ec60)
	/Users/aes/src/ngrok/toolchain/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/Users/aes/src/ngrok/toolchain/src/net/http/transport.go:660 +0xc9f

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc20809ec60)
	/Users/aes/src/ngrok/toolchain/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/Users/aes/src/ngrok/toolchain/src/net/http/transport.go:661 +0xcbc
cforrence@localhost ~  $ 
```

When attempting to update ngrok while running, the terminal window would black out with no output shown to the user.

If ngrok was being run using the binary, the two viable workarounds were to either re-download the binary or to install it via Homebrew.

**Comment by chrisforrence** [comment]
Honestly, given that there are viable workarounds, I can understand this being a lower priority.

**Comment by inconshreveable** [comment]
This is a bug in Mac OSX sierra. there's nothing much we can do about it except ask you to manually updated to the new version which has a workaround for them. sorry!
