### ISSUE TITLE
panic on Linux x86

### ISSUE THREAD

**Issue by erikriverson** [inconshreveable/ngrok#437]
I downloaded https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip , unzip the file, and attempt to run `ngrok help`. I receive this error: 

```
$ ngrok help
panic: getwd: no such file or directory

goroutine 1 [running]:
github.com/go-martini/martini.init.1()
	/Users/alan/src/ngrok/vendor/src/github.com/go-martini/martini/env.go:29 +0xc2
github.com/go-martini/martini.init()
	/Users/alan/src/ngrok/vendor/src/github.com/go-martini/martini/static.go:136 +0x13b
main.init()
	/Users/alan/src/ngrok/src/ngrok/web_ui.go:568 +0x166
```

**Comment by erikriverson** [comment]
nevermind, something was wrong with the terminal I was trying this in . fresh terminal session works just fine, closing.
