### ISSUE TITLE
Not using https proxy

### ISSUE THREAD

**Issue by akshaygarg834** [inconshreveable/ngrok#439]
I have tried installing ngrok globally and in a project as dependency but ngrok seems to show this error 
`
npm install -g ngrok
/home/linuxbrew/.linuxbrew/bin/ngrok -> /home/linuxbrew/.linuxbrew/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.15 postinstall /home/linuxbrew/.linuxbrew/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error downloading binary { Error: tunneling socket could not be established, cause=write EPROTO 139875597596480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

    at ClientRequest.onError (/home/linuxbrew/.linuxbrew/lib/node_modules/ngrok/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7) code: 'ECONNRESET' }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error downloading binary { Error: tunneling socket could not be established, cause=write EPROTO 139875597596480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

    at ClientRequest.onError (/home/linuxbrew/.linuxbrew/lib/node_modules/ngrok/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7) code: 'ECONNRESET' }
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error downloading binary { Error: tunneling socket could not be established, cause=write EPROTO 139875597596480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

    at ClientRequest.onError (/home/linuxbrew/.linuxbrew/lib/node_modules/ngrok/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7) code: 'ECONNRESET' }
ngrok - install failed { Error: tunneling socket could not be established, cause=write EPROTO 139875597596480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

    at ClientRequest.onError (/home/linuxbrew/.linuxbrew/lib/node_modules/ngrok/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7) code: 'ECONNRESET' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.15 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@2.2.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

I thinks its because it is not routing using proxy.
I had same error with npm which I fixed by setting https-proxy in .npmrc file.
If I use internet which doesn't require internet proxy It works fine. On collage internet we have to use proxy. Please provide guidence to resolve this. Also I have a folder .ngrok in home dir not .ngrok2.
Operating Sys Ubuntu 16.04.02
Node Version : v8.1.4
Yarn Version: 0.27.5

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
