### ISSUE TITLE
2.3.25 Segfaults regularly with wordpress

### ISSUE THREAD

**Issue by martenjacobs** [inconshreveable/ngrok#568]
```
ngrok by @inconshreveable                                                           (Ctrl+C to quit)

Session Status                online
Account                       Marten Jacobs (Plan: Basic)
Version                       2.3.25
Region                        Europe (eu)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://<HIDDEN>.eu.ngrok.io -> http://localhost:8081
Forwarding                    https://<HIDDEN>.eu.ngrok.io -> http://localhost:8081
Forwarding                    http://<HIDDEN>.eu.ngrok.io -> http://localhost:8080
Forwarding                    https://<HIDDEN>.eu.ngrok.io -> http://localhost:8080

Connections                   ttl     opn     rt1     rt5     p50     p90
                              0       2       0.00    0.00    0.00    0.00

HTTP Requests
-------------

GET /wp-content/themes/lightblogify/img/bg-img.jpg
GET /wp-content/uploads/2019/04/42608420_470902676736431_5059172544964198400_o.jpg  304 Not Modified
GET /wp-content/themes/lightblogify/justinadlock-customizer-button/customize-contro 200 OK
GET /wp-content/themes/lightblogify/justinadlock-customizer-button/customize-contro 200 OK
GET /wp-admin/customize.php                                                         200 OKpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x134454c]

goroutine 77 [running]:
go.ngrok.com/lib/net/inspect/http.(*inspector).maybeServerSwitchProtocols(0xc0001ee2a0, 0x1e5dcc0, 0xc000286150, 0x0, 0xc000174480)
        /home/vagrant/ngrok/go/lib/net/inspect/http/inspect.go:297 +0x2c
go.ngrok.com/lib/net/inspect/http.(*inspector).readResponses(0xc0001ee2a0, 0x1e5dcc0, 0xc000286150)
        /home/vagrant/ngrok/go/lib/net/inspect/http/inspect.go:287 +0x862
created by go.ngrok.com/lib/net/inspect/http.Inspect
        /home/vagrant/ngrok/go/lib/net/inspect/http/inspect.go:98 +0x289
error Command failed with exit code 2.
```

When accessing the 'Customize' panel in Wordpress I consistently get the above crash in ngrok. This somehow seems to be specific to the LightBlogify theme, as some other theme's I've tried worked fine.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
