### ISSUE TITLE
 tunnelListener failed with error runtime error: makeslice: len out of range: goroutine 3983 [running]

### ISSUE THREAD

**Issue by jianboy** [inconshreveable/ngrok#582]
```
[00:58:02 CST 2019/06/09] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:4f30c04f] New connection from 39.98.236.118:59154
[00:58:02 CST 2019/06/09] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:4f30c04f] Waiting to read message
[00:58:02 CST 2019/06/09] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:4f30c04f] Reading message with length: 4294990336
**[00:58:02 CST 2019/06/09] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:4f30c04f] tunnelListener failed with error runtime error: makeslice: len out of range: goroutine 3983 [running]:**
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
ngrok/server.tunnelListener.func1.1(0xf776d968, 0x188e5b20)
	/media/sf_share/linux/ngrok/src/ngrok/server/main.go:71 +0x43
panic(0x837f3e0, 0x1883ac38)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
ngrok/msg.readMsgShared(0xf776d968, 0x188e5b20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/media/sf_share/linux/ngrok/src/ngrok/msg/conn.go:20 +0x242
ngrok/msg.ReadMsg(0xf776d968, 0x188e5b20, 0x0, 0x0, 0x0, 0x0)
	/media/sf_share/linux/ngrok/src/ngrok/msg/conn.go:37 +0x45
ngrok/server.tunnelListener.func1(0x18720840, 0xf776d968, 0x188e5b20)
	/media/sf_share/linux/ngrok/src/ngrok/server/main.go:77 +0x1bf
created by ngrok/server.tunnelListener
	/media/sf_share/linux/ngrok/src/ngrok/server/main.go:97 +0x206

[00:58:03 CST 2019/06/09] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [metrics] Reporting: {"bytesIn.count":9267824,"bytesOut.count":264159,"connMeter.count":219,"connMeter.m1":2.964393875e-314,"httpTunnelMeter.count":25,"linux":0,"osx":0,"other":0,"tcpTunnelMeter.count":0,"tunnelMeter.count":50,"tunnelMeter.m1":2.964393875e-314,"windows":50}
[00:58:07 CST 2019/06/09] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:5a478af8] New connection from 39.98.236.118:59352
[00:58:07 CST 2019/06/09] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:5a478af8] Waiting to read message
[00:58:08 CST 2019/06/09] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:5a478af8] Reading message with length: 872415506

```

**Comment by vitaliy-kravchenko** [comment]
You must build ngrok-client the same way as ngrok-server from the repository instead of using the latest version.
I'm using Dockerfile for build mac os version:
```
FROM golang:latest
ENV GOOS darwin
ENV GOARCH amd64
RUN git clone https://github.com/inconshreveable/ngrok.git /tmp/ngrok
RUN cd /tmp/ngrok \
    && export GOOS GOARCH \
    && make release-client
```

Then just build, run and copy the client from the container

```
docker build -t ngrok-client-macos .
docker cp $(docker run -d --rm ngrok-client-macos sleep 100):/tmp/ngrok/bin/darwin_amd64/ngrok ./
```

Make it executable and copy it to `/usr/local/bin/`

```
sudo cp ./ngrok /usr/loca/bin/ && sudo chmod +x /usr/loca/bin/ngrok
```

Do not forget to configure `~/.ngrok` file as described in the SELFHOSTING.md

**Comment by zxdposter** [comment]
I have that issue too.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
