### ISSUE TITLE
self host server error

### ISSUE THREAD

**Issue by levyitay** [inconshreveable/ngrok#615]
Hi All, 
Did anyone seen this error:
`[00:29:13 UTC 2019/11/06] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:66d47537] Reading message with length: 2329560872202948419
[00:29:13 UTC 2019/11/06] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:66d47537] tunnelListener failed with error runtime error: makeslice: len out of range: goroutine 291 [running]:
runtime/debug.Stack(0xc0000c7d18, 0x7bfce0, 0x8ae300)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x9d
ngrok/server.tunnelListener.func1.1(0x8c0e00, 0xc00039b240)
	/home/itayl/ngrok/src/ngrok/server/main.go:71 +0x57
panic(0x7bfce0, 0x8ae300)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
ngrok/msg.readMsgShared(0x8c0e00, 0xc00039b240, 0x70fd9b, 0xc0000bfc00, 0xbf68a2d8cf1f9a2c, 0x36917238f3, 0xb43520)
	/home/itayl/ngrok/src/ngrok/msg/conn.go:20 +0x1d0
ngrok/msg.ReadMsg(0x8c0e00, 0xc00039b240, 0x36917238f3, 0xb43520, 0x0, 0x0)
	/home/itayl/ngrok/src/ngrok/msg/conn.go:37 +0x39
ngrok/server.tunnelListener.func1(0xc0000fc5b0, 0x8c0e00, 0xc00039b240)
	/home/itayl/ngrok/src/ngrok/server/main.go:77 +0xe5
created by ngrok/server.tunnelListener
	/home/itayl/ngrok/src/ngrok/server/main.go:67 +0x1a3`

**Comment by zxdposter** [comment]
I have that issue too.

**Comment by levyitay** [comment]
@zxdposter moved to Serveo way easier as long as it's for private use.

**Comment by successcw** [comment]
same issue, I fixed it with following
```
diff --git a/src/ngrok/msg/conn.go b/src/ngrok/msg/conn.go
index 2cc8b99..3fde3c1 100644
--- a/src/ngrok/msg/conn.go
+++ b/src/ngrok/msg/conn.go
@@ -17,6 +17,11 @@ func readMsgShared(c conn.Conn) (buffer []byte, err error) {
        }
        c.Debug("Reading message with length: %d", sz)
 
+    if sz > 10000000000 {
+           c.Debug("bruce invalid length")
+        err = errors.New("invalid length")
+        return
+    }
        buffer = make([]byte, sz)
```

**Comment by PwccaCode** [comment]
> same issue, I fixed it with following
> 
> ```
> diff --git a/src/ngrok/msg/conn.go b/src/ngrok/msg/conn.go
> index 2cc8b99..3fde3c1 100644
> --- a/src/ngrok/msg/conn.go
> +++ b/src/ngrok/msg/conn.go
> @@ -17,6 +17,11 @@ func readMsgShared(c conn.Conn) (buffer []byte, err error) {
>         }
>         c.Debug("Reading message with length: %d", sz)
>  
> +    if sz > 10000000000 {
> +           c.Debug("bruce invalid length")
> +        err = errors.New("invalid length")
> +        return
> +    }
>         buffer = make([]byte, sz)
> ```

func readMsgShared(c conn.Conn) (buffer []byte, err error) {
	c.Debug("Waiting to read message")

	var sz int64
	err = binary.Read(c, binary.LittleEndian, &sz)
	if err != nil {
		return
	}
	c.Debug("test read message: %d", sz)

	if sz > 10000000000 {
			c.Debug("invalid length")
			err = errors.New("invalid length")
			return
	}
	
	buffer = make([]byte, sz)
	n, err := c.Read(buffer)
	c.Debug("Read message %s", buffer)

	if err != nil {
		return
	}

	if int64(n) != sz {
		err = errors.New(fmt.Sprintf("Expected to read %d bytes, but only read %d", sz, n))
		return
	}

	return
}

is this how the full function looks like in your end?

**Comment by successcw** [comment]
yes

Leonardo H. ***@***.***> 于2023年9月8日周五 20:59写道：

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
