### ISSUE TITLE
Ngrok error

### ISSUE THREAD

**Issue by White151** [inconshreveable/ngrok#683]
How can i fix it
[ NGROK SERVER ]!
-------------------------------
t=2020-07-26T00:19:13+0000 lvl=warn msg="failed to get home directory, using $HOME instead" err="user: Current not implemented on linux/arm64" $HOME=/data/data/com.termux/files/home
t=2020-07-26T00:19:13+0000 lvl=eror msg="failed to reconnect session" obj=csess id=2a363953465f err="dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:42261->[::1]:53: read: connection refused"
Traceback (most recent call last):
  File "HiddenEye.py", line 49, in <module>
    server_menu.server_selection(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 47, in server_selection
    server_runner.start_ngrok(port) # FIXED
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_ngrok
    ngrok.connect(port=int(port))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 135, in get_ngrok_process
    return process.get_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 206, in get_process
    return _start_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 329, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:42261->[::1]:53: read: connection refused.

**Comment by caseysoftware** [comment]
Phishing for any reason is a ngrok TOS/AUP violation. Any phishing, hacking, or other malicious activity will result in an immediate ban.
