### ISSUE TITLE
tunnelListener failed with error runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by sunhuwh** [inconshreveable/ngrok#709]
please, can I config the size of message?
I used auth,but then hava some people send this message let my ngrok server down.

[00:30:03 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:12a6f717] New connection from 101.133.131.45:54210
[00:30:03 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:12a6f717] Waiting to read message
[00:30:11 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [metrics] Reporting: {"bytesIn.count":105855035,"bytesOut.count":42685980,"connMeter.count":108520,"connMeter.m1":7.155433267719217e-58,"httpTunnelMeter.count":8,"linux":8,"osx":0,"other":0,"tcpTunnelMeter.count":0,"tunnelMeter.count":8,"tunnelMeter.m1":2.964393875e-314,"windows":0}
[00:30:13 CST 2020/09/24] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [tun:12a6f717] Failed to read message: read tcp 172.16.68.34:4443->101.133.131.45:54210: i/o timeout
[00:30:13 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:12a6f717] Closing
[00:30:13 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:6721e870] New connection from 101.133.131.45:55936
[00:30:13 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:6721e870] Waiting to read message
[00:30:13 CST 2020/09/24] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [tun:6721e870] Failed to read message: tls: client offered an unsupported, maximum protocol version of 300
[00:30:13 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:6721e870] Closing
[00:30:13 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:4e20f3fe] New connection from 101.133.131.45:55960
[00:30:13 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:4e20f3fe] Waiting to read message
[00:30:19 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:4e20f3fe] Reading message with length: 6073139484287059271
[00:30:19 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:4e20f3fe] tunnelListener failed with error runtime error: makeslice: len out of range: goroutine 444524 [running]:
runtime/debug.Stack(0xc0006f1d38, 0x76dbc0, 0x82e950)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
ngrok/server.tunnelListener.func1.1(0x835340, 0xc0002ba100)
	/usr/local/ngrok/src/ngrok/server/main.go:72 +0x57
panic(0x76dbc0, 0x82e950)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
ngrok/msg.readMsgShared(0x835340, 0xc0002ba100, 0xbfd2fbe7d35f8e02, 0x8024301760a5, 0xaa0360, 0x0, 0x0)
	/usr/local/ngrok/src/ngrok/msg/conn.go:20 +0x1ea
ngrok/msg.ReadMsg(0x835340, 0xc0002ba100, 0x8024301760a5, 0xaa0360, 0x0, 0x0)
	/usr/local/ngrok/src/ngrok/msg/conn.go:37 +0x39
ngrok/server.tunnelListener.func1(0xc0001700a0, 0x835340, 0xc0002ba100)
	/usr/local/ngrok/src/ngrok/server/main.go:78 +0xc1
created by ngrok/server.tunnelListener
	/usr/local/ngrok/src/ngrok/server/main.go:68 +0x1a9

[00:30:24 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:274f79c2] New connection from 101.133.131.45:58388
[00:30:24 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:274f79c2] Waiting to read message
[00:30:24 CST 2020/09/24] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [tun:274f79c2] Reading message with length: 2329291534720323663
[00:30:24 CST 2020/09/24] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [tun:274f79c2] tunnelListener failed with error runtime error: makeslice: len out of range: goroutine 444525 [running]:
runtime/debug.Stack(0xc0006f1d38, 0x76dbc0, 0x82e950)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
ngrok/server.tunnelListener.func1.1(0x835340, 0xc0002ba2c0)
	/usr/local/ngrok/src/ngrok/server/main.go:72 +0x57

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
