### ISSUE TITLE
invalid syntax when install ping with pip

### ISSUE THREAD

**Issue by gokaloge** [inconshreveable/ngrok#790]
```
C:\Users\adm>pip install ngrok
Collecting ngrok
  Downloading ngrok-0.1.6.tar.gz (3.5 kB)
Collecting ping
Downloading ping-0.2.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\adm\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\adm\\AppData\\Local\\Temp\\pip-install-pc7i36p6\\ping_172b794f21b64eb6810bee978d938f4e\\setup.py'"'"'; __file__='"'"'C:\\Users\\adm\\AppData\\Local\\Temp\\pip-install-pc7i36p6\\ping_172b794f21b64eb6810bee978d938f4e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\adm\AppData\Local\Temp\pip-pip-egg-info-sxgraya1'
         cwd: C:\Users\adm\AppData\Local\Temp\pip-install-pc7i36p6\ping_172b794f21b64eb6810bee978d938f4e\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\adm\AppData\Local\Temp\pip-install-pc7i36p6\ping_172b794f21b64eb6810bee978d938f4e\setup.py", line 23, in <module>
        from ping import __version__
      File "C:\Users\adm\AppData\Local\Temp\pip-install-pc7i36p6\ping_172b794f21b64eb6810bee978d938f4e\ping.py", line 196
        except socket.error, (errno, msg):
                           ^
    SyntaxError: invalid syntax
    ----------------------------------------
```

**Comment by caseysoftware** [comment]
This repository is not maintained or monitored. For help with this code, please look at one of the publicly available forks.

We recommend that you use the most recent version from ngrok.com/download for active development and support.
